name: Run tests

on: [push, release]

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x run_tests.sh
         /run_tests.sh
      shell: bash
